openapi: 3.0.0
info:
  title: Medium Blogging API
  version: 0.0.1
servers:
  - description: Mock Server
    url: https://mock.medium.com
  - description: "Staging Server"
    url: https://staging.medium.com
  - description: "Beta Server"
    url: https://beta.medium.com
  - description: "Production Server"
    url: https://medium.com
tags:
  - name: Post
    description: Contain every operation about Post Resource
paths:
  /posts:
    post:
      operationId: createPost
      tags:
      - Post
      requestBody:
        $ref: "#/components/requestBodies/PostRequest"
      responses:
        "201":
          $ref: "#/components/responses/PostResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
  /posts/{id}:
    put:
      operationId: updatePost
      tags:
        - Post
      parameters:
        - in: path
          name: id
          description: The id of the Post
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        $ref: "#/components/requestBodies/PostRequest"
      responses:
        "200":
          $ref: "#/components/responses/PostResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
components:
  requestBodies:
    PostRequest:
      description: Payload for making a Post
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                example: Industrial Society and It's Future
              body:
                type: string
                example: |
                  Lorem ipsum dolor sit amet,
                  consectetur adipiscing elit.
                  Nullam quis tristique dolor.
                  Donec at vehicula urna. Fusce nec lacus placerat,
                  dictum nulla quis, vehicula urna.
                  Suspendisse dictum neque sapien,
                  mollis semper quam tincidunt sit amet.
                  Fusce ullamcorper, nisi id pharetra egestas,
                  nisi libero ullamcorper mi,
                  id consectetur enim arcu eget turpis.
                  Fusce urna diam, elementum a diam non,
                  efficitur tempus eros.
                  Nam tincidunt orci vitae enim vulputate vehicula.
                  Nullam commodo magna sed nulla efficitur,
                  in gravida eros malesuada.
                  Quisque vel turpis sed elit
                  finibus luctus et sed leo.
                  Etiam porta metus purus,
                  in vulputate est accumsan a.
                  Aenean pulvinar aliquam nunc,
                  vel pharetra diam sodales in.
  responses:
    ForbiddenResponse:
      description: Response when accessing protected endpoint with access but sufficient access
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: FAIL
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: "FORBIDDEN"
                  message:
                    type: string
                    example: "Invalid access level"
    UnauthorizedResponse:
      description: Response when accessing protected endpoint without access
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: FAIL
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: "UNAUTHORIZED"
                  message:
                    type: string
                    example: "Access is not granted"
    PostResponse:
      description: Response when mutating and get individual Post.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: OK
              data:
                $ref: "#/components/schemas/Post"
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          example: "bdaf6814-2e99-40d5-9c15-e0238a90c886"
        title:
          type: string
          example: Industrial Society and It's Future
        body:
          type: string
          example: |
            Lorem ipsum dolor sit amet,
            consectetur adipiscing elit.
            Nullam quis tristique dolor.
            Donec at vehicula urna. Fusce nec lacus placerat,
            dictum nulla quis, vehicula urna.
            Suspendisse dictum neque sapien,
            mollis semper quam tincidunt sit amet.
            Fusce ullamcorper, nisi id pharetra egestas,
            nisi libero ullamcorper mi,
            id consectetur enim arcu eget turpis.
            Fusce urna diam, elementum a diam non,
            efficitur tempus eros.
            Nam tincidunt orci vitae enim vulputate vehicula.
            Nullam commodo magna sed nulla efficitur,
            in gravida eros malesuada.
            Quisque vel turpis sed elit
            finibus luctus et sed leo.
            Etiam porta metus purus,
            in vulputate est accumsan a.
            Aenean pulvinar aliquam nunc,
            vel pharetra diam sodales in.
        authorId:
          type: string
          example: "196508c4-495f-4d2e-898b-776fb3c1e8b4"
        authorName:
          type: string
          example: "Ted Kaczynski"
        authorAvatar:
          type: string
          example: "https://placekitten.com/200/200"
        createdAt:
          type: string
          example: "2021-07-30 17:00:00 +0700"
        updatedAt:
          type: string
          example: "2021-07-30 17:00:00 +0700"